/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author hamza
 */
public class calculator extends javax.swing.JFrame {
     double num1;
     double num2;
     String operator;
     double result;
     String showresult;
     public double num3;
     public double num4;
      double mresult;
    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
        setSize(525,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtdisplay = new javax.swing.JTextField();
        jbtn1 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtnsqrt = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtndot = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtnmod = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnmultiply = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnplusminus = new javax.swing.JButton();
        jbtnbcksp = new javax.swing.JButton();
        jbtnmemrecal = new javax.swing.JButton();
        jbtneql = new javax.swing.JButton();
        jbtnadd = new javax.swing.JButton();
        jbtnmemsub = new javax.swing.JButton();
        jbtnmemclr = new javax.swing.JButton();
        jbtnsub = new javax.swing.JButton();
        jbtndivide = new javax.swing.JButton();
        jbtnclr = new javax.swing.JButton();
        jbtnmemadd = new javax.swing.JButton();
        jbtnmemstor = new javax.swing.JButton();
        jbtnpow = new javax.swing.JButton();
        jbtnsqr = new javax.swing.JButton();
        jbtnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(412, 312));

        jbtn7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn7.setName("jbtn7"); // NOI18N
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Standard Calculator");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jtxtdisplay.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jtxtdisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtdisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtdisplay.setName("jtxtdisplay"); // NOI18N
        jtxtdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdisplayActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn1.setName("jbtn1"); // NOI18N
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn0.setText("0");
        jbtn0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn0.setName("jbtn0"); // NOI18N
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn4.setName("jbtn4"); // NOI18N
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtnsqrt.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnsqrt.setText("sqrt");
        jbtnsqrt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsqrt.setName("jbtnsqrt"); // NOI18N
        jbtnsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsqrtActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn2.setName("jbtn2"); // NOI18N
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtndot.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtndot.setText(".");
        jbtndot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtndot.setName("jbtndot"); // NOI18N
        jbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndotActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn5.setName("jbtn5"); // NOI18N
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtnmod.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtnmod.setText("%");
        jbtnmod.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnmod.setName("jbtnmod"); // NOI18N
        jbtnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodActionPerformed(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn8.setName("jbtn8"); // NOI18N
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn9.setName("jbtn9"); // NOI18N
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtnmultiply.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtnmultiply.setText("*");
        jbtnmultiply.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnmultiply.setName("jbtnmultiply"); // NOI18N
        jbtnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiplyActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn6.setName("jbtn6"); // NOI18N
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn3.setName("jbtn3"); // NOI18N
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnplusminus.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtnplusminus.setText("+/-");
        jbtnplusminus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnplusminus.setName("jbtnplusminus"); // NOI18N
        jbtnplusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusminusActionPerformed(evt);
            }
        });

        jbtnbcksp.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnbcksp.setText("CE");
        jbtnbcksp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnbcksp.setName("jbtnbcksp"); // NOI18N
        jbtnbcksp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbckspActionPerformed(evt);
            }
        });

        jbtnmemrecal.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnmemrecal.setText("MR");
        jbtnmemrecal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnmemrecal.setName("jbtnmemrecal"); // NOI18N
        jbtnmemrecal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmemrecalActionPerformed(evt);
            }
        });

        jbtneql.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtneql.setText("=");
        jbtneql.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtneql.setName("jbtneql"); // NOI18N
        jbtneql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneqlActionPerformed(evt);
            }
        });

        jbtnadd.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtnadd.setText("+");
        jbtnadd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnadd.setName("jbtnadd"); // NOI18N
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });

        jbtnmemsub.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnmemsub.setText("M-");
        jbtnmemsub.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnmemsub.setName("jbtnmemsub"); // NOI18N
        jbtnmemsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmemsubActionPerformed(evt);
            }
        });

        jbtnmemclr.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnmemclr.setText("MC");
        jbtnmemclr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnmemclr.setName("jbtnmemclr"); // NOI18N
        jbtnmemclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmemclrActionPerformed(evt);
            }
        });

        jbtnsub.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtnsub.setText("-");
        jbtnsub.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsub.setName("jbtnsub"); // NOI18N
        jbtnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsubActionPerformed(evt);
            }
        });

        jbtndivide.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtndivide.setText("/");
        jbtndivide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtndivide.setName("jbtndivide"); // NOI18N
        jbtndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivideActionPerformed(evt);
            }
        });

        jbtnclr.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnclr.setText("C");
        jbtnclr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnclr.setName("jbtnclr"); // NOI18N
        jbtnclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclrActionPerformed(evt);
            }
        });

        jbtnmemadd.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnmemadd.setText("M+");
        jbtnmemadd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnmemadd.setName("jbtnmemadd"); // NOI18N
        jbtnmemadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmemaddActionPerformed(evt);
            }
        });

        jbtnmemstor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnmemstor.setText("MS");
        jbtnmemstor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnmemstor.setName("jbtnmemstor"); // NOI18N
        jbtnmemstor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmemstorActionPerformed(evt);
            }
        });

        jbtnpow.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnpow.setText("pow");
        jbtnpow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnpow.setName("jbtnpow"); // NOI18N
        jbtnpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpowActionPerformed(evt);
            }
        });

        jbtnsqr.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnsqr.setText("^2");
        jbtnsqr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsqr.setName("jbtnsqr"); // NOI18N
        jbtnsqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsqrActionPerformed(evt);
            }
        });

        jbtnexit.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnexit.setText("Exit");
        jbtnexit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnexit.setName("jbtnexit"); // NOI18N
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtdisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnmod, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnsqr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnmemadd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnpow, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(jbtnmemstor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnmemrecal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnclr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnplusminus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnbcksp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtneql, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnmemsub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnmemclr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnexit)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jtxtdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnmemrecal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnmemstor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnpow, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnmemadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnmod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnsqr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnclr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbtnmemsub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnplusminus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnbcksp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnmemclr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtneql, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdisplayActionPerformed

    private void jbtnmemrecalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmemrecalActionPerformed
        showresult = String.valueOf(mresult);
        jtxtdisplay.setText(showresult);
    }//GEN-LAST:event_jbtnmemrecalActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
      //jtxtdisplay.setText(jbtn7.getText());
        String Enternum = jtxtdisplay.getText()+jbtn7.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String Enternum = jtxtdisplay.getText()+jbtn8.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String Enternum = jtxtdisplay.getText()+jbtn9.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String Enternum = jtxtdisplay.getText()+jbtn4.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String Enternum = jtxtdisplay.getText()+jbtn5.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String Enternum = jtxtdisplay.getText()+jbtn6.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String Enternum = jtxtdisplay.getText()+jbtn1.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
       String Enternum = jtxtdisplay.getText()+jbtn2.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String Enternum = jtxtdisplay.getText()+jbtn3.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String Enternum = jtxtdisplay.getText()+jbtn0.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
         num1 = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText(" ");
        operator = "+";
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplyActionPerformed
        num1 = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText(" ");
        operator = "*";
    }//GEN-LAST:event_jbtnmultiplyActionPerformed

    private void jbtnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsubActionPerformed
         num1 = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText(" ");
        operator = "-";
    }//GEN-LAST:event_jbtnsubActionPerformed

    private void jbtndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivideActionPerformed
         num1 = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText(" ");
        operator = "/";
    }//GEN-LAST:event_jbtndivideActionPerformed

    private void jbtnclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclrActionPerformed
        jtxtdisplay.setText(" ");
        
        
    }//GEN-LAST:event_jbtnclrActionPerformed

    private void jbtnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodActionPerformed
        num1 = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText(" ");
        operator = "%";
    }//GEN-LAST:event_jbtnmodActionPerformed

    private void jbtneqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneqlActionPerformed
       num2 = Double.parseDouble(jtxtdisplay.getText());
      if(operator == "+"){
          result = num1 + num2;
          showresult = String.format("%,2f",result);
          jtxtdisplay.setText(showresult);
      }
       else if(operator == "-"){
           result =  num1 - num2;
           showresult = String.format("%.2f", result);
           jtxtdisplay.setText(showresult);
       }
       else if(operator == "*"){
           result =  num1 * num2;
           showresult = String.format("%.2f", result);
           jtxtdisplay.setText(showresult);
       }
       else if(operator  == "/"){
           result =  num1 / num2;
           showresult = String.format("%.2f", result);
           jtxtdisplay.setText(showresult);
       }
       else if(operator  == "%"){
           result =  num1 % num2;
           showresult = String.format("%.2f", result);
           jtxtdisplay.setText(showresult);
       }
    }//GEN-LAST:event_jbtneqlActionPerformed

    private void jbtnbckspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbckspActionPerformed
        String backspace = "";
        if (jtxtdisplay.getText().length() > 0){
            StringBuilder sb = new StringBuilder(jtxtdisplay.getText());
            sb.deleteCharAt(jtxtdisplay.getText().length() -1);
            backspace = sb.toString();
            jtxtdisplay.setText(backspace);
        }
        
    }//GEN-LAST:event_jbtnbckspActionPerformed

    private void jbtnmemstorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmemstorActionPerformed
        num3 = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText(null);
    }//GEN-LAST:event_jbtnmemstorActionPerformed

    private void jbtnmemaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmemaddActionPerformed
       try{
         
        num4 = Double.parseDouble(jtxtdisplay.getText());
        mresult = num3 + num4;
     
        jtxtdisplay.setText(null);
       }
       catch(Exception e){
           System.out.println("not important");
       }
//       jtxtdisplay.setText(showresult);
        
    }//GEN-LAST:event_jbtnmemaddActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
         String Enternum = jtxtdisplay.getText()+jbtndot.getText();
       jtxtdisplay.setText(Enternum);
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtnmemsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmemsubActionPerformed
         try{
           num4 = Double.parseDouble(jtxtdisplay.getText());
          mresult = num4 - num3;
          
          jtxtdisplay.setText(null);
       }
       catch(Exception e){
           System.out.println("not important");
       }
       
    }//GEN-LAST:event_jbtnmemsubActionPerformed

    private void jbtnmemclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmemclrActionPerformed
       mresult = 0;
       jtxtdisplay.setText(" ");
       
    }//GEN-LAST:event_jbtnmemclrActionPerformed

    private void jbtnsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsqrtActionPerformed
        double d = Math.sqrt(Double.parseDouble(jtxtdisplay.getText()));
        jtxtdisplay.setText(String.valueOf(d));
    }//GEN-LAST:event_jbtnsqrtActionPerformed

    private void jbtnplusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusminusActionPerformed
         double opr = Double.parseDouble(jtxtdisplay.getText());
         opr *= -1;
         jtxtdisplay.setText(String.valueOf(opr));
    }//GEN-LAST:event_jbtnplusminusActionPerformed

    private void jbtnpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpowActionPerformed
        double p = Double.parseDouble(jtxtdisplay.getText());
        double pow = Math.pow(p, p);
        jtxtdisplay.setText(String.format("%,3f",pow));
        
        
    }//GEN-LAST:event_jbtnpowActionPerformed

    private void jbtnsqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsqrActionPerformed
        double p = Double.parseDouble(jtxtdisplay.getText());
        double pow = Math.pow(p, 2);
        jtxtdisplay.setText(String.format("%,3f",pow));
    }//GEN-LAST:event_jbtnsqrActionPerformed

    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnbcksp;
    private javax.swing.JButton jbtnclr;
    private javax.swing.JButton jbtndivide;
    private javax.swing.JButton jbtndot;
    private javax.swing.JButton jbtneql;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnmemadd;
    private javax.swing.JButton jbtnmemclr;
    private javax.swing.JButton jbtnmemrecal;
    private javax.swing.JButton jbtnmemstor;
    private javax.swing.JButton jbtnmemsub;
    private javax.swing.JButton jbtnmod;
    private javax.swing.JButton jbtnmultiply;
    private javax.swing.JButton jbtnplusminus;
    private javax.swing.JButton jbtnpow;
    private javax.swing.JButton jbtnsqr;
    private javax.swing.JButton jbtnsqrt;
    private javax.swing.JButton jbtnsub;
    private javax.swing.JTextField jtxtdisplay;
    // End of variables declaration//GEN-END:variables
}
